### ISSUE TITLE
Take snapshot not working on queued constructions

### ISSUE THREAD

**Issue by TheMule71** [0Mayall/ONIMods#9]
Hi!
I'm quite sure that in the past I was able to queue a few buildings (like in a unreachable area), and the copy and past those via the snapshot tool. Now I can't do that anymore, it copies only objects that are actually built. Is this the intended behaviour? Is there an option to revert to the old behaviour?

**Comment by 0Mayall** [comment]
Hi, thanks for the report. This issue has been fixed in 2.3.305.0 (incorrectly labeled as 2.2.305.0 in this repo.) It’s likely steam has not pushed this version to you yet. You might want to consider manually updating the mod. Please comment whether the issue still persists for you beyond 2.3.305.0. If not I will close this issue.
